[gcp_service_account]
type = "service_account"
project_id = "gx-dashboard-478118"
private_key_id = "776d81c441ea4759acd8212ed84bd0a33c104eae"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDMRX+Lz1bbSazn
125oGVO2DdcB9IKbxSR4UoLxMk0o/7klCsjHRIW8oKy1gkho1rHyKz6goHBtSvpn
BBWv0QMAB9+cEJu2PvLZm/yh6S0AFkBCob9cg9pCwhSohMODAJ6A0oVE9G8C2Zqh
Zf1zVMPrGFhOCFneih0g5DkAgJeoNA2IhXZhnxEM7RxzK0UN9hIZuwWisB7DE+Iz
dOUnNyOCWJrfkuA21R3FxEuEo3YyR7sBfEPbGWU0n4xy59qeRIe58fM9op+yOXMy
F8APv7udDNAWIm3lKYLP2Ns1LPOW/A4LC1WQgy3cQ+pxb3EZmra5vAhn4eYgqiBF
OjFpn4wPAgMBAAECggEASg5CHN4453xQ3qZ4JO5VrnFbCx7pgO6ad7K2PRpW5e+7
4CWGP9PkRkvcAVvvw25eieTKqjIwQDdIC7Pr5tc4Jrk0BKDyysIMif7muo5OHbNz
bZS1SyWUKdKx6ZxkQyikziBEZ4jUfCyGxk+y8K6A7sjfLr8RUcAxqjyDO97i3HwI
INYOKJW6Fpyn/j6DdJxT+G2Wt7+32xL5gvQQZfT0rGGW2nMWqPw2a0+2E7tP7hzd
5CQwY1KqVvgBJP5/lmEsahoj8dkxFv6NjDObd2F/AJlf6G1lkJQIGNEzY6oPc0PU
V5IgwPcMEg3fdIXeJ6mkGjIT3zmTuIfDM33ubWezKQKBgQD5iC6f8Cn5YzztRPIt
y6fLGUa9Bebi4GV0lV0XGmBAZYw9L1J4mabhaTt/qaTkXQ9W4dPKgKuP2lQymj6G
OQRHjUWR/0W0GZFx7SAJgylzq83dJk1yyWzRMYrdwLsJ2aMo7xA61+jDLbNrSs+I
HF23jj/wKGvQfM9N2d8ufF7S1wKBgQDRkPs582q7Ep6p4hmh1I1gzeTDjuXz3VmI
rcexEO9yUIenUQlniEo6tRFyZO1YO4RR51aUwiaHzmMpZI7L1s1Uo1FUChadz+xZ
GJtVvTrDNASEnhIbAcZJaF/XZnnoFm3OsDf6QvJATdzYfWqQHqLuyIzSVVm57NkF
JMOYqIUhiQKBgQDzQdg6IPW6Yg0WPV1eWag07WoxgZxo1lrxgV6j1Bm7DYPebdCX
MyslmeHf/XB7E2GN0E8YncEiVrQ4NHf5f4H1gvosbs/z1+0bRBA0VcJGOllRWzKr
UUOc2BBJR8bOvnU5xXxr8Om/xEChuueACC8wbyNTqwQX1mR9v4S8G5CRNwKBgE1s
6DSX50XocjBHtbqhgf5S84MAx5qanBqwQcf8fsrYT9YUTYovw2T/Qsvl1/6yNofg
FY/uTzf7m41Odqd+2+u6TzDibUqu6B5exf0eZZh7HnQ0xnGt7Slv44D8fmut5bHo
TzYqB8CUQ9TEOVu3xfC8rbKEEBtuExwgYheDo3QpAoGALK2ljHy0Z+FaSadvuDxo
ytBfv3CqQ7xEZROZUVAA8w/Tj3NYRheYWyX+ZGW9GlusaTnDMoDmA6DwI2OSA/sH
N+0Rg0Zal9EqdcKhUtvYkzXVCUcTYDGPX1sWcCg+rfRskKS7GTzxNSX/VPww3+ld
Lv/TKdWndPmqnW0RqMXv6EI=
-----END PRIVATE KEY-----"""
client_email = "gx-bot@gx-dashboard-478118.iam.gserviceaccount.com"
client_id = "112943513429454043938"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gx-bot%40gx-dashboard-478118.iam.gserviceaccount.com"
universe_domain = "googleapis.com"